### ISSUE TITLE
Self-heal cannot fix a Java compile error within its attempt budget

### ISSUE THREAD

**Issue by piyushmakhija28** [techdeveloper-org/lordcode#62]
First honest end-to-end Java result after #59 stopped the false pass.

```
$ vishwakarma run "add a REST endpoint for creating an order" --lang java
Attempt 0: FAILED
Attempt 1: FAILED
Attempt 2: FAILED
Attempt 3: FAILED
```

The generation is substantial and mostly right -- 13 source files plus **3 test classes** in the
correct `src/test/java` layout, a `GlobalExceptionHandler`, DTOs, repository, service. It does not
compile:

```
GlobalExceptionHandler.java:[31,5] method does not override or implement a method from a supertype
GlobalExceptionHandler.java:[48,5] method does not override or implement a method from a supertype
GlobalExceptionHandler.java:[66,38] cannot find symbol
  symbol:   method getIdempotencyKey()
  location: variable ex of type com.example.orders.exception.OrderAlreadyExistsException
```

Both are ordinary, mechanical faults: a stray `@Override` on methods that override nothing, and a
getter referenced on an exception class that does not declare it. A competent Java developer fixes
both in under a minute, and the compiler names the file, line and symbol.

## Why four attempts did not fix it -- hypotheses, none yet measured

1. **One attempt was spent on a different fault.** Attempt 0 failed with #59's *"No test files were
   generated"*, so the first heal went on writing tests, not on compiling (#61). Only ~3 attempts
   ever saw the compile error.
2. **The diagnosis may not be receiving the compiler output.** This is the one to check first. If the
   reasoner is handed a truncated log, or the Maven output is being summarised before it reaches the
   prompt, then it is being asked to fix an error it cannot see. Maven now runs without `-q` (#59),
   so the output is *much* larger than before -- a plausible truncation point that did not exist
   yesterday, and one this fix introduced.
3. **Budget.** `MAX_CODER_TOKENS` is 8000 against an 8000 TPM ceiling; a 13-file Java project plus
   compiler output plus prior-attempt history may simply not fit, so each regeneration may be
   working from a partial view and re-breaking what it fixed.
4. **Regeneration versus repair.** The loop regenerates files rather than patching them, so a fix to
   `GlobalExceptionHandler` can arrive alongside a fresh mistake elsewhere -- an attempt can make
   things worse and nothing detects that it has.

## What to measure before changing anything

- Print or log exactly what the reasoner receives on a Java heal attempt. If the compiler errors are
  absent or truncated, that is the whole bug and hypothesis 2 ends the investigation.
- Record error count per attempt across the 4 attempts. Monotonically decreasing means the loop is
  converging and just needs budget; oscillating means hypothesis 4.
- Compare against the Python path, which recovers reliably -- the difference between them is the
  evidence.

## Context

Not a regression: before #59 this same run reported *"All tests passed"* over seven files and zero
tests. It now fails honestly on a real defect, which is a considerable improvement and also the first
time this failure mode has been visible at all. The Python path recovers within the loop (6/6 passing
after one heal), so the machinery works -- something about the Java path specifically does not.

**Comment by piyushmakhija28** [comment]
Fixed in 0d3d99c, merged as PR #63, released in **1.0.4**.

**Hypothesis 2 from the issue body was wrong** -- I suspected #59's removal of Maven's `-q` had pushed
the compiler errors past the 3000-char truncation. Measured: the first `ERROR` is at char **1686**.
Recorded because it was my own suspicion about my own change.

Three real causes, each sufficient alone:

1. The 6000-char file budget was spent in generation order (alphabetical), omitting **10 of 16 files
   including BOTH the compiler named** -- the reasoner was asked to fix code it had never seen, so no
   attempt budget could have worked.
2. `current_files = artifact.files` **replaced** the file list, so the model's view shrank each
   attempt while the runner kept compiling everything from disk.
3. Filename matching alone still missed the mark: javac names *types*
   (`location: variable ex of type ...OrderAlreadyExistsException`), never the filename.

Fixing (1) then blew the input ceiling -- `413 Request too large, ITPM Limit 7000, Requested 7127` --
because the history block repeated the entire file listing per attempt. It now carries paths plus the
error and no source.

| | before | after |
|---|---|---|
| prompt | 7,912 tokens (413s) | **3,957** |
| broken files | omitted | **full** |
| visible lines | 41 | **103** |
| original errors fixed | 0 | **3 of 4** |

**Not green yet, and the remaining failure is a different shape:** the loop now converges then
oscillates (3 → 1 → 5 errors), because an attempt can break a file an earlier attempt changed.
Tracked as #64 -- it was unreachable while the loop could fix nothing.

8 tests added with the control embedded in each (assert the un-prioritised path omits the file, then
that the prioritised one does not), so the fixture cannot silently stop reproducing the bug.
671 pass.
